INT: modify default job example
redis/docs pull request #1003
Opened 2024-12-19 14:52 UTC by dwdougherty

[DOC-4682](https://redislabs.atlassian.net/browse/DOC-4682)

[DOC-4682]: https://redislabs.atlassian.net/browse/DOC-4682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-19 17:02 UTC, cmilesb approved these changes
Looks good to me!

2024-12-19 17:03 UTC, dwdougherty commented
Thank you, @cmilesb!

2024-12-22 07:11 UTC, spicy-sauce requested changes

2024-12-22 07:11 UTC, spicy-sauce commented on content/integrate/write-behind/data-transformation/data-transformation-pipeline.md
> -  row_format: full
I'm not sure if line 53 will still work if we remove it here, we probably should come up with a better example.
BTW, it also seems that this example is scaffolded in `default.yaml.example`, not sure if this ideal - @yaronp68

2025-01-02 14:38 UTC, dwdougherty commented on content/integrate/write-behind/data-transformation/data-transformation-pipeline.md
> -  row_format: full
I did what was stated in the JIRA ticket. This will have to sit until @andy-stark-redis is back from PTO.

2025-02-25 16:09 UTC, closed without merging