Updates to AI Dev Hub page
redis/docs pull request #1007
Opened 2024-12-19 22:45 UTC by jcaw07

I updated the AI Dev Hub index page with the following changes:
- Added additional resources and links for AI learning materials
- Added brief descriptions for each section and guide to the page
- Add 2 image files used in the AI Dev Hub page
- Fixed broken links that went to Colab notebooks

I worked to follow Michelle’s previous layout while adding new content. Please let me know any feedback on my submitted changes. Thanks.

JAWS

2024-12-19 22:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redis/docs?pullRequest=1007) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redis/docs?pullRequest=1007) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redis/docs?pullRequest=1007) it.</sub>

2025-01-02 19:04 UTC, mich-elle-luna requested changes
Thank you! Just a few editorial changes.

2025-01-02 19:04 UTC, mich-elle-luna commented on content/develop/ai/index.md
> +* [RAG workbench](https://github.com/redis-developer/redis-rag-workbench) - A development playground for exploring RAG techniques with Redis.
remove period

2025-01-02 19:04 UTC, mich-elle-luna commented on content/develop/ai/index.md
> +* [Redis product search](https://github.com/redis-developer/redis-product-search) - Build a real-time product search engine using features like full-text search, vector similarity, and real-time data
remove period

2025-01-02 19:04 UTC, mich-elle-luna commented on content/develop/ai/index.md
> +See how we stack up against the competition.
Redis Vector benchmark results.

2025-01-02 19:04 UTC, mich-elle-luna commented on content/develop/ai/index.md
> +* [get better RAG responses with Ragas](https://redis.io/blog/get-better-rag-responses-with-ragas/)
Get

2025-01-08 23:39 UTC, jcaw07 commented on content/develop/ai/index.md
> +## Overview
Ok great. I changed it to heading 4

2025-01-08 23:41 UTC, jcaw07 commented on content/develop/ai/index.md
> +* **Concepts** - Explanations of foundational ideas and core principles to help you understand the "why" behind the product’s features and design.
Updated

2025-01-08 23:42 UTC, jcaw07 commented on content/develop/ai/index.md
> +| Search | LLM memory | Semantic caching | Semantic routing | AI Gateways |
fixed

2025-01-08 23:42 UTC, jcaw07 commented on content/develop/ai/index.md
> +Quickstarts or recipes are for when you are trying to build specific functionality. For example, you might want to do RAG with LangChain or set up LLM memory for you AI agent. Get started with the fo
Fixed

2025-01-08 23:43 UTC, jcaw07 commented on content/develop/ai/index.md
> +* [RAG workbench](https://github.com/redis-developer/redis-rag-workbench) - A development playground for exploring RAG techniques with Redis.
done

2025-01-08 23:43 UTC, jcaw07 commented on content/develop/ai/index.md
> +* [Redis product search](https://github.com/redis-developer/redis-product-search) - Build a real-time product search engine using features like full-text search, vector similarity, and real-time data
done

2025-01-08 23:44 UTC, jcaw07 commented on content/develop/ai/index.md
> +See how we stack up against the competition.
updated

2025-01-08 23:44 UTC, jcaw07 commented on content/develop/ai/index.md
> +* [get better RAG responses with Ragas](https://redis.io/blog/get-better-rag-responses-with-ragas/)
Fixed

2025-01-08 23:45 UTC, jcaw07 commented on content/develop/ai/index.md
> +* **Docs** - The comprehensive reference section for every feature, API, and setting. It’s your source for detailed, technical information to support any level of development.
Changed to How to's

2025-01-08 23:45 UTC, jcaw07 commented on content/develop/ai/index.md
> +* **Quickstarts** - Short, focused guides to get you up and running with key features or workflows in minutes.
Changed

2025-01-10 23:19 UTC, mich-elle-luna reviewed
thank you! this is looking good, just need to resize the new images to match the others (they are too large)

2025-01-14 00:41 UTC, jcaw07 commented
Thanks! I updated the images to match the size of the other icons.

2025-01-14 21:38 UTC, mich-elle-luna approved these changes
thank you!

2025-01-14 21:40 UTC, merged