Update the sequence of commands in install-on-linux.md
redis/docs pull request #155
Opened 2024-04-29 18:39 UTC by grvsoni

dpkg-sig --verify  need to run on installation package (*.deb) which is only available after
```
sh tar vxf <tarfile name>
```

2024-04-29 19:09 UTC, dwdougherty commented
@rrelledge This LGTM, but since it's your area, can you review and approve?

2024-04-30 15:56 UTC, rrelledge requested changes
Thanks, @grvsoni. I suggest keeping "Copy the installation package to the node" as the first step before extracting the installation files, and then making the optional GPG section its own numbered step.

2024-04-30 15:56 UTC, rrelledge commented on content/operate/rs/installing-upgrading/install/install-on-linux.md
> +
```suggestion

1. Copy the installation package to the node.

```

2024-04-30 15:56 UTC, rrelledge commented on content/operate/rs/installing-upgrading/install/install-on-linux.md
>  1. Copy the installation package to the node.
```suggestion
```

2024-04-30 15:56 UTC, rrelledge commented on content/operate/rs/installing-upgrading/install/install-on-linux.md
> +    _(Optional)_ Use the {{< download "GPG key file" "../GPG-KEY-redislabs-packages.gpg" >}} to confirm the authenticity of Ubuntu/Debian or RHEL RPM packages:
```suggestion
1.  _(Optional)_ Use the {{< download "GPG key file" "../GPG-KEY-redislabs-packages.gpg" >}} to confirm the authenticity of Ubuntu/Debian or RHEL RPM packages:
```

2024-04-30 15:59 UTC, rrelledge commented on content/operate/rs/installing-upgrading/install/install-on-linux.md
> +To install Redis Enterprise Software use the command line:
```suggestion
To install Redis Enterprise Software, use the command line:
```

2024-05-02 14:08 UTC, dwdougherty approved these changes
LGTM. Thank you, @rrelledge, for the review.

2024-05-02 14:14 UTC, merged