expiration fixes
redis/docs pull request #169
Opened 2024-05-03 13:49 UTC by adrianoamaral

align the messaging (FT.AGGREGATE and FT.SEARCH) and make it more clear when a key expires during a query execution, what should be the expected behaviour. So the key name it's still return, but the value should be nil

2024-05-03 13:50 UTC, adrianoamaral commented
@dwdougherty please revise and merge. Tks

2024-05-03 16:12 UTC, dwdougherty commented on content/commands/ft.search/index.md
> +- If a key expires during the query, an attempt to load the key's value will return a null array. The key is still counted in the total number of results
```suggestion
- If a relevant key expires while a query is running, an attempt to load the key's value will return a null array. However, the key is still counted in the total number of results.
```

2024-05-03 16:13 UTC, dwdougherty requested changes
Just one comment, @adrianoamaral . Thank you!

2024-05-06 13:31 UTC, dwdougherty approved these changes

2024-05-06 13:35 UTC, merged