K8s: change pvc warning to link to new feature
redis/docs pull request #312
Opened 2024-06-11 17:18 UTC by kaitlynmichael

2024-06-11 17:25 UTC, dwdougherty requested changes
A couple of link issues. See suggestions.

2024-06-11 17:25 UTC, dwdougherty commented on content/operate/kubernetes/recommendations/persistent-volumes.md
> +Persistent volume claims can be expanded, but not reduced after creation. See [Expand PersistentVolumeClaim (PVC)]({{relref "/operate/kubernetes/re-clusters/expand-pvc"}}) for details.
Link doesn't display.

```suggestion
Persistent volume claims can be expanded, but not reduced after creation. See [Expand PersistentVolumeClaim (PVC)]({< {relref "/operate/kubernetes/re-clusters/expand-pvc" >}}) for details.
```

2024-06-11 17:25 UTC, dwdougherty commented on content/operate/kubernetes/recommendations/sizing-on-kubernetes.md
> +Persistent volume claims can be expanded, but not reduced after creation. See [Expand PersistentVolumeClaim (PVC)]({{relref "/operate/kubernetes/re-clusters/expand-pvc"}}) for details.
```suggestion
Persistent volume claims can be expanded, but not reduced after creation. See [Expand PersistentVolumeClaim (PVC)]({{< relref "/operate/kubernetes/re-clusters/expand-pvc" >}}) for details.
```

2024-06-17 19:36 UTC, kaitlynmichael commented on content/operate/kubernetes/recommendations/persistent-volumes.md
> +Persistent volume claims can be expanded, but not reduced after creation. See [Expand PersistentVolumeClaim (PVC)]({{relref "/operate/kubernetes/re-clusters/expand-pvc"}}) for details.
```suggestion
Persistent volume claims can be expanded, but not reduced after creation. See [Expand PersistentVolumeClaim (PVC)]({{<relref "/operate/kubernetes/re-clusters/expand-pvc">}}) for details.
```

2024-06-17 19:36 UTC, merged