DOC-3907 added transform info lost from the old docs
redis/docs pull request #337
Opened 2024-06-19 14:43 UTC by andy-stark-redis

Added information about transformations that was present in the [old docs](https://github.com/redis/docs/blob/DOC-3755-csharp-client-intro/content/integrate/redis-data-integration/data-transformation/data-transformation-pipeline.md) but lost from the new ingest docs.

I've dropped old sections that referred to MongoDB and Cassandra, since I believe these aren't available as ingest sources currently. I've also assumed that Redis is the only available target database type for ingest.

2024-06-19 15:02 UTC, yaronp68 requested changes
the content is mish-mashed between config.yaml and job

2024-06-19 15:02 UTC, yaronp68 commented on content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
>      supply a unique composite key.
this is a mistake I have missed previously. needs to be removed

2024-06-19 15:02 UTC, yaronp68 commented on content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
>  - `advanced`: These optional properties configure other Debezium-specific features.
all of the advanced content is nested under the main source section

2024-06-20 08:48 UTC, andy-stark-redis commented on content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
> +- [*Write-behind*]({{< relref "/integrate/redis-data-integration/write-behind/architecture" >}})
Done.

2024-06-20 08:48 UTC, andy-stark-redis commented on content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
> +type that is suitable for the target. RDI provides a default transformation
Hopefully improved now.

2024-06-20 08:49 UTC, andy-stark-redis commented on content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
> +[Debezium](https://debezium.io/) is automatically transformed to a Redis JSON format. Then,
Done.

2024-06-20 08:49 UTC, andy-stark-redis commented on content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
> +.
Done.

2024-06-20 08:51 UTC, yaronp68 approved these changes

2024-06-20 08:53 UTC, merged