Fix outdated relref to client-eviction
redis/docs pull request #390
Opened 2024-07-02 08:59 UTC by dzoech

2024-07-02 13:52 UTC, dwdougherty requested changes
Thank you @dzoech ! Much appreciated. Just a couple of comments:

1. Corrected link spec.

1. There's one more occurrence of this link further below. Would you please fix it as well?

2024-07-02 13:52 UTC, dwdougherty commented on content/commands/client-no-evict/index.md
> +The `CLIENT NO-EVICT` command sets the [client eviction]({{< relref "/develop/reference/clients/#client-eviction" >}}) mode for the current connection.
```suggestion
The `CLIENT NO-EVICT` command sets the [client eviction]{{< relref "/develop/reference/clients">}}#client-eviction) mode for the current connection.
```

2024-07-09 19:47 UTC, dwdougherty approved these changes
LGTM. Thanks again, @dzoech !

2024-07-09 19:49 UTC, merged

2024-07-09 21:01 UTC, dzoech commented
Sorry I must have missed the notification about your comment. Thanks for updating.