Provide additional information for setting timeout settings when configuring the Lettuce driver
redis/docs pull request #395
Opened 2024-07-03 11:58 UTC by tishun

Added a section to the documentation of the Lettuce driver that specifically deals with timeouts.
The example given is of setting a socket timeouts that a few of our clients have requested recently to deal with connectivity issues. To give examples about all the timeouts would have perhaps been too verbose and some of them are very specific.

2024-07-05 15:09 UTC, mich-elle-luna reviewed
thank you!

2024-07-08 14:36 UTC, dwdougherty requested changes
Thank you, @tishun ! A few editorial changes are necessary.

2024-07-08 14:36 UTC, dwdougherty commented on content/develop/connect/clients/java/lettuce.md
> +Unless configured otherwise, Lettuce uses a global timeout of 60 seconds. You can set the timeout for each operation individually.
```suggestion
### Timouts
Lettuce provides timeouts for many operations, such as command execution, SSL handshake, and Sentinel discovery. By default, Lettuce uses a global timeout value of 60 seconds for these operations, but you can override the global timeout value with individual timeout values for each operation.
```

2024-07-08 14:36 UTC, dwdougherty commented on content/develop/connect/clients/java/lettuce.md
> +For more details on setting specific timeouts, see the [Lettuce reference guide](https://lettuce.io/core/release/reference/index.html).
```suggestion
Choosing suitable timeout values is crucial for your application's performance and stability and is specific to each environment.
Configuring timeouts is only necessary if you have issues with the default values. 
In some cases, the defaults are based on environment-specific settings (e.g., operating system settings), while in other cases, they are built into the Lettuce driver. 
For more details on setting specific timeouts, see the [Lettuce reference guide](https://lettuce.io/core/release/reference/index.html).
```

2024-07-08 14:36 UTC, dwdougherty commented on content/develop/connect/clients/java/lettuce.md
> +Below is a example of setting a typical socket-level timeouts. The `TCP_USER_TIMEOUT` is useful for scenarios where the server stops responding without acknowledging the last request, while the `KEEP
```suggestion
Below is an example of setting socket-level timeouts. The `TCP_USER_TIMEOUT` setting is useful for scenarios where the server stops responding without acknowledging the last request, while the `KEEPALIVE` setting is good for detecting dead connections where there is no traffic between the client and the server.
```

2024-07-09 11:56 UTC, tishun commented
> Thank you, @tishun ! A few editorial changes are necessary.

Awesome, much better, thanks for helping with this!

2024-07-09 13:33 UTC, dwdougherty approved these changes
LGTM

2024-07-09 13:33 UTC, merged