RC: resilient apps tip
redis/docs pull request #553
Opened 2024-08-15 15:22 UTC by kaitlynmichael

2024-08-15 15:28 UTC, mich-elle-luna approved these changes
One change to make the title match, otherwise looks good. Thank you!

2024-08-15 15:28 UTC, mich-elle-luna commented on content/operate/rc/subscriptions/maintenance/_index.md
> +To make sure your applications reconnect to your database quickly after maintenance, see [Resilient applications with Redis Cloud]({{< relref "/operate/rc/resilient-apps" >}}).
```suggestion
To make sure your applications reconnect to your database quickly after maintenance, see [Develop highly available and resilient apps with Redis Cloud]({{< relref "/operate/rc/resilient-apps" >}}).
```

2024-08-18 12:41 UTC, NoamSternRedis requested changes

2024-08-18 12:41 UTC, NoamSternRedis commented on content/operate/rc/subscriptions/maintenance/_index.md
> +To make sure your applications reconnect to your database quickly after maintenance, see [Develop highly available and resilient apps with Redis Cloud]({{< relref "/operate/rc/resilient-apps" >}}).
Let's drop the word "quickly". It's problematic in our world and depends on the user. 
I would say something like "To make sure your applications are set to reconnect after maintenance activity"

2024-08-21 16:46 UTC, kaitlynmichael commented on content/operate/rc/subscriptions/maintenance/_index.md
> +To make sure your applications reconnect to your database quickly after maintenance, see [Develop highly available and resilient apps with Redis Cloud]({{< relref "/operate/rc/resilient-apps" >}}).
```suggestion
To make sure your applications are set to reconnect after maintenance activity, see [Develop highly available and resilient apps with Redis Cloud]({{< relref "/operate/rc/resilient-apps" >}}).
```

2024-08-22 10:23 UTC, NoamSternRedis approved these changes

2024-08-27 16:10 UTC, merged