K8s: code block spacing fix
redis/docs pull request #695
Opened 2024-09-24 19:27 UTC by kaitlynmichael

DOC-2151

2024-09-24 19:36 UTC, cmilesb requested changes
There's one note that still has a spacing issue. The rest look okay.

2024-09-24 19:36 UTC, cmilesb commented on content/operate/kubernetes/deployment/openshift/openshift-cli.md
The note on Line 113 in this file also has a spacing issue.

2024-09-24 19:39 UTC, dwdougherty reviewed
Just one comment.

2024-09-24 19:39 UTC, dwdougherty commented on content/embeds/k8s-admission-webhook-cert.md
> +```
This item doesn't have the same indentation as the others above it, and it kinda sticks out like a sore thumb. Same for the other page. All the code examples should have uniform indentation.

2024-09-26 13:34 UTC, cmilesb approved these changes
Looks good!

2024-09-30 15:01 UTC, merged