FLUSH commands and functions
redis/docs pull request #762
Opened 2024-10-14 08:55 UTC by LiorKogan

2024-10-14 08:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redis/docs?pullRequest=762) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redis/docs?pullRequest=762) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redis/docs?pullRequest=762) it.</sub>

2024-10-14 09:09 UTC, oranagra commented
@LiorKogan do you expect me to read the diff and somehow figure out what was changed in that long line and why??
please add a description to the PR to make it easier.

2024-10-14 09:18 UTC, LiorKogan commented
Northing was changed in that long line. I change "note" to "notes" and added a new note - functions are not deleted.

2024-10-14 14:31 UTC, oranagra approved these changes

2024-10-15 13:42 UTC, dwdougherty requested changes
Just a couple of minor issues.

2024-10-15 13:42 UTC, dwdougherty commented on content/commands/flushall/index.md
> +* This commands does not delete functions
```suggestion
* This command does not delete functions.
```

2024-10-15 13:42 UTC, dwdougherty commented on content/commands/flushdb/index.md
> +* This commands does not delete functions
```suggestion
* This command does not delete functions.
```

2024-10-15 15:04 UTC, dwdougherty approved these changes

2024-10-15 15:05 UTC, dwdougherty approved these changes
LGTM. Merging.

2024-10-15 15:16 UTC, merged