DOC-4607 added debezium_lob_encoded_placeholder prop to config.yaml
redis/docs pull request #935
Opened 2024-11-28 14:56 UTC by andy-stark-redis

[DOC-4607](https://redislabs.atlassian.net/browse/DOC-4607)

2024-11-29 13:26 UTC, loriotpiroloriol commented
Please change to this (uncomment `processors`; LOBs are large objects, not just binary; correct indent):
```
processors:
# Enable Debezium LOB placeholders for tables that contain large objects.
# Uncomment this property (and the `processors:` section) if your tables include
# Oracle large objects (BLOB, CLOB, NCLOB).
#  debezium_lob_encoded_placeholder: X19kZWJleml1bV91bmF2YWlsYWJsZV92YWx1ZQ==
```

2024-11-29 13:45 UTC, loriotpiroloriol requested changes

2024-11-29 13:45 UTC, loriotpiroloriol commented on content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
> +#     debezium_lob_encoded_placeholder: X19kZWJleml1bV91bmF2YWlsYWJsZV92YWx1ZQ==
```suggestion
processors:
# Enable Debezium LOB placeholders for tables that contain large objects.
# Uncomment this property (and the `processors:` section) if your tables include
# Oracle large objects (BLOB, CLOB, NCLOB).
#  debezium_lob_encoded_placeholder: X19kZWJleml1bV91bmF2YWlsYWJsZV92YWx1ZQ==
```

2024-12-02 14:35 UTC, dwdougherty approved these changes
LGTM.

2024-12-02 14:37 UTC, merged