DOC-4647 updated supported sources table with AWS RDS details
redis/docs pull request #974
Opened 2024-12-11 09:26 UTC by andy-stark-redis

I got the details of the supported AWS RDS databases from the existing pages - please check if they're all correct. Also, I got the supported version of Aurora/PostgreSQL from [this screenshot](https://redislabs.atlassian.net/wiki/spaces/~6318b461316bbc56c425f7f9/pages/4753588337/RDI+with+AWS+Aurora+and+PostgreSQL#Create-Aurora-PostgreSQL-DB-cluster) in George's original document - please let me know if we need to add any other supported versions here.

2024-12-12 11:49 UTC, yaronp68 requested changes

2024-12-12 11:49 UTC, yaronp68 commented on content/integrate/redis-data-integration/architecture.md
> +| Database                    | Versions               | Supports Amazon RDS |
Amazon RDS supports several db types.
We support RDS MySQL, RDS Oracle, RDS SQL Server, RDS Postgres, RDS Mariadb with the same versions we support on prem
(List of supported versions can be updated based on Debezium 2.7 support matrix)

2024-12-12 11:50 UTC, yaronp68 commented on content/integrate/redis-data-integration/architecture.md
> +| Database                    | Versions               | Supports Amazon RDS |
https://debezium.io/releases/

2024-12-13 10:13 UTC, andy-stark-redis commented
@yaronp68 Thanks for the info. I've added it and I've also made an embeddable version of the table so it will be consistent wherever we use it.

2024-12-13 10:26 UTC, yaronp68 requested changes

2024-12-13 10:26 UTC, yaronp68 commented on content/integrate/redis-data-integration/_index.md
The table is inconsistent now in structure. RDS is a column while google sqls are rows
We can decide we make all cloud support columns and types of database are rows. that's ok
In this case google versions will move to the right of RDS

2024-12-13 10:58 UTC, andy-stark-redis commented on content/integrate/redis-data-integration/_index.md
@yaronp68 OK, I've tidied it up. Also, I based the AlloyDB version info on the table [here](https://cloud.google.com/alloydb/docs/db-version-policies#support-table).

2024-12-13 11:55 UTC, yaronp68 requested changes

2024-12-13 11:55 UTC, yaronp68 commented on content/embeds/rdi-supported-source-versions.md
> +| Database | Versions | Versions for Amazon RDS | Versions for Google Cloud SQL |
```suggestion
| Database | Versions | AWS RDS  Versions | GCP SQL Versions |
```

2024-12-13 18:58 UTC, yaronp68 approved these changes

2024-12-13 19:48 UTC, merged